name: CI/CD LiteCommerce

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Build Docker (CI check)
      - name: Build Admin Docker Image
        run: docker build -f Dockerfile.admin -t admin-app:test .

      - name: Build Shop Docker Image
        run: docker build -f Dockerfile.shop -t shop-app:test .

      # Publish artifacts
      - name: Publish Admin
        run: dotnet publish SV22T1020063.Admin/SV22T1020063.Admin.csproj -c Release -o ./publish-admin

      - name: Publish Shop
        run: dotnet publish SV22T1020063.Shop/SV22T1020063.Shop.csproj -c Release -o ./publish-shop

      # Upload artifacts để job khác dùng lại
      - name: Upload Admin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: admin-package
          path: ./publish-admin

      - name: Upload Shop Artifact
        uses: actions/upload-artifact@v4
        with:
          name: shop-package
          path: ./publish-shop

  deploy-admin:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: production-admin
      url: https://sv22t1020063-litecommerce-admin-f8azgnb7fnhegna7.japaneast-01.azurewebsites.net

    steps:
      - name: Download Admin Artifact
        uses: actions/download-artifact@v4
        with:
          name: admin-package
          path: ./publish-admin

      - name: Deploy Admin to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'sv22t1020063-litecommerce-admin'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_ADMIN }}
          package: ./publish-admin

  deploy-shop:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: production-shop
      url: https://sv22t1020063-litecommerce-shop-fwezc2aua3btc8gw.japaneast-01.azurewebsites.net

    steps:
      - name: Download Shop Artifact
        uses: actions/download-artifact@v4
        with:
          name: shop-package
          path: ./publish-shop

      - name: Deploy Shop to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'sv22t1020063-litecommerce-shop'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_SHOP }}
          package: ./publish-shop

      - name: Deploy Shop to Render
        run: curl -X GET ${{ secrets.RENDER_DEPLOY_HOOK_SHOP }}