name: CI/CD LiteCommerce Docker

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://sv22t1020063-litecommerce.onrender.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Render (Shop)
        run: |
          echo "Deploying Shop..."
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_SHOP }}

      - name: Deploy to Render (Admin)
        run: |
          echo "Deploying Admin..."
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_ADMIN }}